type: reward
start: 0
end: None
stop: 0
ctx_dir: reward_inference_mjlab
ctx_path: reward_locomotion.pkl
selected_rewards_filter_z:
  - reward: "move-ego-low0.5-0-0"
    z_ids: [0]
  - reward: "move-ego-90-0.3"
    z_ids: [0]
  - reward: "move-ego-0-0"
    z_ids: [0]
  - reward: "spin-arms-5-l-l"
    z_ids: [0]
