type: tracking
start: 0
end: 200000
stop: 0

# Local sim2sim default. For robot teleop, change this to:
#   tcp://<WORKSTATION_IP>:28711
ctx_source: zmq
ctx_zmq_addr: tcp://127.0.0.1:28711
ctx_norm_ref: 16.0

gamma: 0.8
window_size: 3
